=== Martussoun/seminarka/ZJ/XML/seminarka_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="user"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer" />
				<xs:element name="jmeno" type="xs:string" />
				<xs:element name="prijmeni" type="xs:string" />
				<xs:element name="uzivatelske_jmeno" type="xs:string" />
				<xs:element name="email" type="xs:string" />
				<xs:element name="mobil" type="xs:integer" />
				<xs:element name="hry" type="hry" />
				<xs:element name="wishlists" type="wishlists" />
				<xs:element name="platformy" type="platforma_list"></xs:element>
			</xs:sequence>
			<xs:attribute name="VIP" type="xs:boolean" />
		</xs:complexType>
	</xs:element>

	<xs:element name="platforma">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer" />
				<xs:element name="nazev" type="xs:string" />
				<xs:element name="stranka" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="platforma_list">
		<xs:sequence>
			<xs:element ref="platforma" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="hra">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer" />
				<xs:element name="titul" type="xs:string" />
				<xs:element name="zanr" type="xs:string" />
				<xs:element name="popis" type="xs:string" />
				<xs:element name="rok_vydani" type="xs:decimal" />
				<xs:element name="cena" type="xs:float" />
				<xs:element name="mena" type="xs:string"></xs:element>
			</xs:sequence>
			<xs:attribute name="oblibene" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="hry">
		<xs:sequence>
			<xs:element ref="hra" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="group">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer" />
				<xs:element minOccurs="1" maxOccurs="1" ref="hra" />
			</xs:sequence>
			<xs:attribute name="vlastnictvi" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="group_list">
		<xs:sequence>
			<xs:element ref="group" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="wishlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer" />
				<xs:element name="nazev" type="xs:string" />
				<xs:element name="datum_vytvoreni" type="xs:date" />
				<xs:element name="groups" type="group_list" />
			</xs:sequence>
			<xs:attribute name="verejny" type="xs:boolean" />
			<xs:attribute name="aktivni" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="wishlists">
		<xs:sequence>
			<xs:element ref="wishlist" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Martussoun/seminarka/ZJ/XML/seminarka_data.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="seminarka_styl.xsl"?>

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="seminarka_schema.xsd">

	<user VIP="true">
		<id>0</id>
		<jmeno>Petr</jmeno>
		<prijmeni>Tupý</prijmeni>
		<uzivatelske_jmeno>Zabijak123</uzivatelske_jmeno>
		<email>petrik04@gmail.com</email>
		<mobil>720884213</mobil>
		<hry>	
			<hra oblibene="true">
				<id>0</id>
				<titul>Rise of the Tomb Raider</titul>
				<zanr>Dobrodružné</zanr>
				<popis>Rise of the Tomb Raider popisuje osudy Lary Croft a Jonaha Maiava v jejich pátrání po starověkém městě Kitezh na Sibiři, které bylo postaveno v 13. století, a jak Lara věří, skrývá tajemství k nesmrtelnosti. V závodě s Trinity, dobře financovanou organizací zajímající se o nadpřirozeno, musí Lara bojovat s lidmi, zvěří a přírodou, pokud chce najít pravdu, skrývající se za mýty a stát se tím, kým je předurčena se stát.</popis>
				<rok_vydani>2015</rok_vydani>
				<cena>29.99</cena>
				<mena>EUR</mena>
			</hra>
			<hra oblibene="true">
				<id>1</id>
				<titul>Counter-Strike: Global Offensive</titul>
				<zanr>Střílečka</zanr>
				<popis>Counter-Strike: Global Offensive je počítačová online FPS. Hru vyvinulo Valve ve spolupráci s Hidden Path Entertainment. Hra navazuje na předchozí verze hry Counter-Strike. Je to v pořadí již čtvrtá hra ze série Counter-Strike.				</popis>
				<rok_vydani>2012</rok_vydani>
				<cena>0.00</cena>
				<mena>EUR</mena>
			</hra>
		</hry>
		<wishlists>
			<wishlist verejny="true" aktivni="true">
				<id>0</id>
				<nazev>Tochci</nazev>
				<datum_vytvoreni>2014-06-07</datum_vytvoreni>
				<groups>
					<group vlastnictvi="true">
						<id>0</id>
						<hra oblibene="true">
							<id>1</id>
							<titul>Rise of the tomb raider</titul>
							<zanr>Akcni</zanr>
							<popis>Rise of the Tomb Raider popisuje osudy Lary Croft a Jonaha Maiava v jejich pátrání po starověkém městě Kitezh na Sibiři, které bylo postaveno v 13. století, a jak Lara věří, skrývá tajemství k nesmrtelnosti. V závodě s Trinity, dobře financovanou organizací zajímající se o nadpřirozeno, musí Lara bojovat s lidmi, zvěří a přírodou, pokud chce najít pravdu, skrývající se za mýty a stát se tím, kým je předurčena se stát.</popis>
							<rok_vydani>2015</rok_vydani>
							<cena>29.99</cena>
							<mena>EUR</mena>
						</hra>
					</group>
				</groups>
			</wishlist>
		</wishlists>
		<platformy>
			<platforma>
				<id>0</id>
				<nazev>Steam</nazev>
				<stranka>https://store.steampowered.com/</stranka>
			</platforma>
		</platformy>
	</user>

	<user VIP="true">
		<id>1</id>
		<jmeno>Vojtěch</jmeno>
		<prijmeni>Ostrý</prijmeni>
		<uzivatelske_jmeno>iceteaEnjoyer</uzivatelske_jmeno>
		<email>asdfgj@post.cz</email>
		<mobil>779546218</mobil>
		<hry>	
			<hra oblibene="true">
				<id>1</id>
				<titul>Counter-Strike: Global Offensive</titul>
				<zanr>Střílečka</zanr>
				<popis>Counter-Strike: Global Offensive je počítačová online FPS. Hru vyvinulo Valve ve spolupráci s Hidden Path Entertainment. Hra navazuje na předchozí verze hry Counter-Strike. Je to v pořadí již čtvrtá hra ze série Counter-Strike.				</popis>
				<rok_vydani>2012</rok_vydani>
				<cena>0.00</cena>
				<mena>EUR</mena>
			</hra>
		</hry>
		<wishlists>
			<wishlist verejny="true" aktivni="false">
				<id>0</id>
				<nazev>cskooo</nazev>
				<datum_vytvoreni>2011-06-07</datum_vytvoreni>
				<groups>
					<group vlastnictvi="true">
						<id>0</id>
						<hra oblibene="true">
							<id>1</id>
							<titul>Counter-Strike: Global Offensive</titul>
							<zanr>Střílečka</zanr>
							<popis>Counter-Strike: Global Offensive je počítačová online FPS. Hru vyvinulo Valve ve spolupráci s Hidden Path Entertainment. Hra navazuje na předchozí verze hry Counter-Strike. Je to v pořadí již čtvrtá hra ze série Counter-Strike.				</popis>
							<rok_vydani>2012</rok_vydani>
							<cena>0.00</cena>
							<mena>EUR</mena>
						</hra>
					</group>
				</groups>
			</wishlist>
		</wishlists>
		<platformy>
			<platforma>
				<id>0</id>
				<nazev>Steam</nazev>
				<stranka>https://store.steampowered.com/</stranka>
			</platforma>
		</platformy>
	</user>

	<user VIP="true">
		<id>2</id>
		<jmeno>Jan</jmeno>
		<prijmeni>Omáčka</prijmeni>
		<uzivatelske_jmeno>n00bDestroyer</uzivatelske_jmeno>
		<email>johnnyom@gmail.com</email>
		<mobil>731485165</mobil>
		<hry>	
			<hra oblibene="false">
				<id>2</id>
				<titul>The Binding of Isaac</titul>
				<zanr>Rogue-like</zanr>
				<popis>The Binding of Isaac je akční RPG střílečka s náhodně generovanými úrovněmi se silnými elementy žánru Rogue-like. Během Isaacovy cesty bude hráč nacházet bizarní poklady, které změní samotnou Isaacovu podstatu, propůjčí mu superschopnosti a dovolí mu tak vymýtit neskutečné příšery, objevovat tajemství a probojovat si cestu ke svobodě.</popis>
				<rok_vydani>2011</rok_vydani>
				<cena>4.99</cena>
				<mena>EUR</mena>
			</hra>
			<hra oblibene="true">
				<id>3</id>
				<titul>Portal 2</titul>
				<zanr>FPS puzzle</zanr>
				<popis>pokračování původní hry Portal, která byla v roce 2007 vydána pouze jako doplněk balíčku Orange box. Hlavní postavou hry je opět Chell, původně pouze testovací objekt v Aperture Science. Chell se tentokrát probouzí ve své stázové komoře a snaží se nadobro již opustit ruiny bývalého komplexu Aperture. Hra také nabízí hru více hráčů v kooperativním režimu. Dva hráči mohou hrát za roboty Atlas a P-Body vytvořené GLaDOS za účelem výzkumu bez rizika nevypočitatelných lidských faktorů chování. Každý hráč má vlastní portálovou pistoli a prochází jednotlivé místnosti společně.</popis>
				<rok_vydani>2011</rok_vydani>
				<cena>8.19</cena>
				<mena>EUR</mena>
			</hra>
		</hry>
		<wishlists>
			<wishlist verejny="false" aktivni="false">
				<id>0</id>
				<nazev>Nepojmenovaný</nazev>
				<datum_vytvoreni>2006-11-09</datum_vytvoreni>
				<groups>
					<group vlastnictvi="true">
						<id>0</id>
						<hra oblibene="true">
							<id>0</id>
							<titul>Portal 2</titul>
							<zanr>FPS puzzle</zanr>
							<popis>pokračování původní hry Portal, která byla v roce 2007 vydána pouze jako doplněk balíčku Orange box. Hlavní postavou hry je opět Chell, původně pouze testovací objekt v Aperture Science. Chell se tentokrát probouzí ve své stázové komoře a snaží se nadobro již opustit ruiny bývalého komplexu Aperture. Hra také nabízí hru více hráčů v kooperativním režimu. Dva hráči mohou hrát za roboty Atlas a P-Body vytvořené GLaDOS za účelem výzkumu bez rizika nevypočitatelných lidských faktorů chování. Každý hráč má vlastní portálovou pistoli a prochází jednotlivé místnosti společně.</popis>
							<rok_vydani>2011</rok_vydani>
							<cena>8.19</cena>
							<mena>EUR</mena>
						</hra>
					</group>
				</groups>
			</wishlist>
		</wishlists>
		<platformy>
			<platforma>
				<id>0</id>
				<nazev>Steam</nazev>
				<stranka>https://store.steampowered.com/</stranka>
			</platforma>
		</platformy>
	</user>

	<user VIP="true">
		<id>3</id>
		<jmeno>Jakub</jmeno>
		<prijmeni>Frajer</prijmeni>
		<uzivatelske_jmeno>Supervize</uzivatelske_jmeno>
		<email>nicitel90@seznam.cz</email>
		<mobil>725584235</mobil>
		<hry>	
			<hra oblibene="true">
				<id>0</id>
				<titul>Rise of the Tomb Raider</titul>
				<zanr>Dobrodružné</zanr>
				<popis>Rise of the Tomb Raider popisuje osudy Lary Croft a Jonaha Maiava v jejich pátrání po starověkém městě Kitezh na Sibiři, které bylo postaveno v 13. století, a jak Lara věří, skrývá tajemství k nesmrtelnosti. V závodě s Trinity, dobře financovanou organizací zajímající se o nadpřirozeno, musí Lara bojovat s lidmi, zvěří a přírodou, pokud chce najít pravdu, skrývající se za mýty a stát se tím, kým je předurčena se stát.</popis>
				<rok_vydani>2015</rok_vydani>
				<cena>29.99</cena>
				<mena>EUR</mena>
			</hra>
			<hra oblibene="true">
				<id>1</id>
				<titul>Counter-Strike: Global Offensive</titul>
				<zanr>Střílečka</zanr>
				<popis>Counter-Strike: Global Offensive je počítačová online FPS. Hru vyvinulo Valve ve spolupráci s Hidden Path Entertainment. Hra navazuje na předchozí verze hry Counter-Strike. Je to v pořadí již čtvrtá hra ze série Counter-Strike.				</popis>
				<rok_vydani>2012</rok_vydani>
				<cena>0.00</cena>
				<mena>EUR</mena>
			</hra>
		</hry>
		<wishlists>
			<wishlist verejny="true" aktivni="true">
				<id>0</id>
				<nazev>Sandbox</nazev>
				<datum_vytvoreni>2010-01-02</datum_vytvoreni>
				<groups>
					<group vlastnictvi="false">
						<id>0</id>
						<hra oblibene="false">
							<id>4</id>
							<titul>Terraria</titul>
							<zanr>Sandbox</zanr>
							<popis>Hra je zaměřená na průzkum světa, budování a boji s nepřáteli - hlavně tedy s bossy - v náhodně generovaném 2D světě.</popis>
							<rok_vydani>2011</rok_vydani>
							<cena>9.99</cena>
							<mena>EUR</mena>
						</hra>
					</group>
				</groups>
			</wishlist>
		</wishlists>
		<platformy>
			<platforma>
				<id>0</id>
				<nazev>Steam</nazev>
				<stranka>https://store.steampowered.com/</stranka>
			</platforma>
		</platformy>
	</user>

	<user VIP="true">
		<id>4</id>
		<jmeno>Otakar</jmeno>
		<prijmeni>Pero</prijmeni>
		<uzivatelske_jmeno>Bouchac99</uzivatelske_jmeno>
		<email>otaper0@seznam.cz</email>
		<mobil>738985148</mobil>
		<hry>	
			<hra oblibene="true">
			<id>1</id>
			<titul>The Binding of Isaac</titul>
			<zanr>Rogue-like</zanr>
